### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by 373005226** [sea-team/simpleui#220]
**你希望增加什么功能？**
** what features do you wish to add? * *
1.
2.
3.

**你希望哪些方面得到优化？**
1.在点击图片显示的时候，图片会直接这样显示，而没有办法返回之前的状态，比如
![image](https://user-images.githubusercontent.com/28999580/71964979-b508d100-3239-11ea-84a1-659903051044.png)
这个时候就只能关掉标签重新打开，这个能否做出优化，类似点击图片就把图片居中在网页显示，然后点击其他地方就可以关掉图片呢
2. 那个有时候刷新后会出现如下问题
![image](https://user-images.githubusercontent.com/28999580/71965163-1b8def00-323a-11ea-8b96-7da6d35a6662.png)
而不显示左边的栏目

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：373005226
E-mail：373005226@qq.com

**Comment by Abraverman666** [comment]
正在解决图片预览问题……

**Comment by newpanjing** [comment]
已经在2.9.2中增加预览功能。
