### ISSUE TITLE
添加过滤器后页面显示异常

### ISSUE THREAD

**Issue by bijack** [sea-team/simpleui#223]
**bug描述**

简单的描述下遇到的bug：添加过滤器后，内容无法填满整个页面，右边留出一片空白（像刚好是之前过滤器所占用的空间），没有添加过滤器的页面则无这个问题。
![image](https://user-images.githubusercontent.com/59827095/72307493-7057bc80-36b5-11ea-9f8e-c13233cfaa9b.png)

**重现步骤**
** repeat step **
1.添加过滤器；
2.开DEBUG，删除缓存；
3.打开有过滤器的页面和无过滤器的页面进行对比。

**环境**

1.Operating System：Linux

2.Python Version：3.8.1

3.Django Version：2.2.6

4.SimpleUI Version：3.9

**Comment by newpanjing** [comment]
请检查自己的过滤器代码 是否某些静态资源无法正常加载。
